version: "3.9"

services:
  # MariaDB for all services
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /mnt/aether/docker-data/wordpress_db:/var/lib/mysql
      - /mnt/aether/docker-data/drupal_db:/var/lib/mysql
      - /mnt/aether/docker-data/laravel_db:/var/lib/mysql
      - /mnt/aether/docker-backend/nextcloud/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - aether-backend
    mem_limit: 2g

  # Nextcloud service
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${NEXTCLOUD_DB}
      MYSQL_USER: ${NEXTCLOUD_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_PASSWORD}
      VIRTUAL_HOST: ${NEXTCLOUD_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${NEXTCLOUD_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /mnt/aetherteam/nextcloud/backend/html:/var/www/html
      - /mnt/aetherteam/nextcloud/backend/data:/var/www/html/data
    ports:
      - "8080:80"
    networks:
      - aether-backend
      - aether-local
      - aether-public
    mem_limit: 2g

  # WordPress service
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${WORDPRESS_DB}
      MYSQL_USER: ${WORDPRESS_USER}
      MYSQL_PASSWORD: ${WORDPRESS_PASSWORD}
      VIRTUAL_HOST: ${WORDPRESS_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${WORDPRESS_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /mnt/aether/docker-data/wordpress/html:/var/www/html
      - /mnt/aether/docker-data/wordpress/data:/var/www/html/wp-content/uploads
    ports:
      - "8081:80"
    networks:
      - aether-backend
      - aether-local
      - aether-public
    mem_limit: 2g

  # Drupal service
  drupal:
    image: drupal:latest
    container_name: drupal
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${DRUPAL_DB}
      MYSQL_USER: ${DRUPAL_USER}
      MYSQL_PASSWORD: ${DRUPAL_PASSWORD}
      VIRTUAL_HOST: ${DRUPAL_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${DRUPAL_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /mnt/aether/docker-data/drupal/html:/var/www/html
      - /mnt/aether/docker-data/drupal/data:/var/www/html/sites/default/files
    ports:
      - "8082:80"
    networks:
      - aether-backend
      - aether-local
      - aether-public
    mem_limit: 2g

  # Laravel service
  laravel:
    image: laravel:latest
    container_name: laravel-app
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${LARAVEL_DB}
      MYSQL_USER: ${LARAVEL_USER}
      MYSQL_PASSWORD: ${LARAVEL_PASSWORD}
      VIRTUAL_HOST: ${LARAVEL_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LARAVEL_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /mnt/aether/docker-data/laravel/html:/var/www/html
      - /mnt/aether/docker-data/laravel/data:/var/www/html/storage
    ports:
      - "8083:80"
    networks:
      - aether-backend
      - aether-local
      - aether-public
    mem_limit: 2g

  # Local NGINX reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - nextcloud
      - wordpress
      - drupal
      - laravel
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
    volumes:
      - /mnt/aether/docker-backend/nginx:/etc/nginx/conf.d
    ports:
      - "8880:80"
      - "8443:443"
    networks:
      - aether-local
      - aether-backend
    mem_limit: 2g

  # Public NGINX-Proxy reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/aether/docker-backend/nginx/certs:/etc/nginx/certs
      - /mnt/aether/docker-backend/nginx/vhost:/etc/nginx/vhost.d
      - /mnt/aether/docker-backend/nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - aether-public
    mem_limit: 2g

  # Let's Encrypt SSL companion for NGINX-Proxy
  nginx-proxy-acme:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/aether/docker-backend/nginx/certs:/etc/nginx/certs
      - /mnt/aether/docker-backend/nginx/vhost:/etc/nginx/vhost.d
      - /mnt/aether/docker-backend/nginx/html:/usr/share/nginx/html
    networks:
      - aether-public
    mem_limit: 2g

networks:
  aether-backend:
    driver: bridge
  aether-local:
    driver: bridge
  aether-public:
    driver: bridge
